CREATE TABLE IF NOT EXISTS visas (
    id SERIAL PRIMARY KEY,
    code VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    customer_id INTEGER,
    customer_name VARCHAR(255) NOT NULL,
    customer_phone VARCHAR(50),
    customer_type VARCHAR(50) DEFAULT 'Cá nhân',
    status VARCHAR(50) DEFAULT 'Tạo mới',
    market VARCHAR(100),
    visa_type VARCHAR(100),
    receipt_date DATE,
    result_date DATE,
    fingerprint_date DATE,
    stamp_date DATE,
    return_date DATE,
    quantity INTEGER DEFAULT 1,
    service_package VARCHAR(255),
    is_urgent BOOLEAN DEFAULT false,
    is_evisa BOOLEAN DEFAULT false,
    exchange_rate NUMERIC DEFAULT 1,
    booking_code VARCHAR(100),
    branch VARCHAR(100),
    notes TEXT,
    created_by INTEGER,
    handled_by INTEGER,
    finance_data JSONB DEFAULT '[]',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS visa_members (
    id SERIAL PRIMARY KEY,
    visa_id INTEGER REFERENCES visas(id) ON DELETE CASCADE,
    fullname VARCHAR(255) NOT NULL,
    passport_number VARCHAR(100),
    passport_url TEXT,
    phone VARCHAR(50),
    dob DATE,
    age_type VARCHAR(50) DEFAULT 'Người lớn',
    checklist_data JSONB DEFAULT '[]',
    evaluation_data JSONB DEFAULT '{}',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
